FLAG = ['Carry','TMP_ZF','BIT']

STEP_DIRECT_ADDRESS = [['NEXT_BYTE'],['FLASH_OUT','RAR_IN']]
STEP_PC_ADD_OFFSET = [['FLASH_OUT','ALU_A_DBUS_L8IN'],["ALUEXT_TWO_CMP","ALU_B_IN"],["PC_OUT","ALUADDRTE","ALU_A_IN"],['ALU_ADD','ALUADDRTE','ALUTOADDR','PC_IN']]
FLAG_INSTRUCTION ={
    'Carry':{
    },
    'TMP_ZF':{
    },
    'BIT':{
    }   
}